apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  destination:
    namespace: promtail
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision:   6.17.0 
    chart: promtail
    helm:
      values: |

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
